#!/usr/bin/env bash
# Create / remove a virtual Focusrite Scarlett 18i20-style interface for local testing
# without the physical USB box (or root, for the ALSA path).
#
# What you get:
#   - ALSA PCMs named "Scarlett 18i20 USB" that accept many channels (plug → default).
#     JamStudio's plug-and-play logic scores them as a multi-IO interface.
#   - Optional PipeWire sink/source with the same description (system mixer visibility).
#
# Usage:
#   ./scripts/virtual-scarlett-18i20.sh start    # install ALSA + PipeWire virtual devices
#   ./scripts/virtual-scarlett-18i20.sh stop     # remove them
#   ./scripts/virtual-scarlett-18i20.sh status   # show what's active
#   ./scripts/virtual-scarlett-18i20.sh alsa     # ALSA only
#   ./scripts/virtual-scarlett-18i20.sh pipewire # PipeWire only
#
# Then restart JamStudio and open Help → Audio Interface…
# Expect something like:
#   In: Scarlett 18i20 USB  |  Out: Built-in / HDA …  (plug-and-play)
# or Same device mode using Scarlett for both.

set -euo pipefail

NAME="Scarlett 18i20 USB"
NODE_OUT="JamStudio-Scarlett18i20-Out"
NODE_IN="JamStudio-Scarlett18i20-In"
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/jamstudio"
ALSA_SNIPPET="$CONF_DIR/alsa-virtual-scarlett.conf"
ASOUNDRC="${HOME}/.asoundrc"
MARKER_BEGIN="# >>> jamstudio-virtual-scarlett (managed) >>>"
MARKER_END="# <<< jamstudio-virtual-scarlett (managed) <<<"
STATE_DIR="$CONF_DIR/virtual-scarlett"
PW_OUT_ID_FILE="$STATE_DIR/pw-out.id"
PW_IN_ID_FILE="$STATE_DIR/pw-in.id"

# Soft multi-channel ends: apps may open up to 20 outs / 18 ins; plug downmixes
# to the machine's real default device (usually stereo speakers/headphones).
write_alsa_snippet() {
    mkdir -p "$CONF_DIR"
    cat > "$ALSA_SNIPPET" << EOF
# Auto-generated by scripts/virtual-scarlett-18i20.sh — do not edit by hand.
# Virtual multi-channel PCMs that fold into the system default device.

pcm.scarlett18i20 {
    type plug
    slave.pcm "default"
    hint {
        show on
        description "${NAME}"
    }
}

# Explicit capture alias (same underlying device; helps some scanners)
pcm.scarlett18i20_in {
    type plug
    slave.pcm "default"
    hint {
        show on
        description "${NAME}"
    }
}

# Playback-only alias
pcm.scarlett18i20_out {
    type plug
    slave.pcm "default"
    hint {
        show on
        description "${NAME}"
    }
}
EOF
}

ensure_asoundrc_include() {
    write_alsa_snippet

    if [[ -f "$ASOUNDRC" ]] && grep -qF "$MARKER_BEGIN" "$ASOUNDRC" 2>/dev/null; then
        # Refresh managed block
        local tmp
        tmp="$(mktemp)"
        awk -v b="$MARKER_BEGIN" -v e="$MARKER_END" '
            $0 == b {skip=1; next}
            $0 == e {skip=0; next}
            !skip {print}
        ' "$ASOUNDRC" > "$tmp"
        mv "$tmp" "$ASOUNDRC"
    fi

    {
        echo ""
        echo "$MARKER_BEGIN"
        echo "<${ALSA_SNIPPET}>"
        echo "$MARKER_END"
    } >> "$ASOUNDRC"

    echo "ALSA: wrote $ALSA_SNIPPET"
    echo "ALSA: ensured include in $ASOUNDRC"
}

remove_asoundrc_include() {
    if [[ -f "$ASOUNDRC" ]] && grep -qF "$MARKER_BEGIN" "$ASOUNDRC" 2>/dev/null; then
        local tmp
        tmp="$(mktemp)"
        awk -v b="$MARKER_BEGIN" -v e="$MARKER_END" '
            $0 == b {skip=1; next}
            $0 == e {skip=0; next}
            !skip {print}
        ' "$ASOUNDRC" > "$tmp"
        mv "$tmp" "$ASOUNDRC"
        echo "ALSA: removed managed block from $ASOUNDRC"
    else
        echo "ALSA: no managed block in $ASOUNDRC"
    fi
    rm -f "$ALSA_SNIPPET"
}

start_pipewire() {
    mkdir -p "$STATE_DIR"

    if ! command -v pw-cli >/dev/null 2>&1; then
        echo "PipeWire: pw-cli not found — skip (ALSA path still works for JamStudio)."
        return 0
    fi

    # 8-channel positions (enough to look like multi-IO; full 18/20 is awkward in PW props)
    local pos='[FL FR FC LFE RL RR SL SR]'

    # Avoid duplicates if already running
    if pw-cli ls Node 2>/dev/null | grep -q "node.name = \"${NODE_OUT}\""; then
        echo "PipeWire: sink ${NODE_OUT} already present"
    else
        pw-cli create-node adapter "{ factory.name=support.null-audio-sink node.name=${NODE_OUT} node.description=\"${NAME}\" media.class=Audio/Sink object.linger=1 audio.channels=8 audio.position=${pos} monitor.channel-volumes=true }" \
            >/dev/null
        echo "PipeWire: created sink \"${NAME}\" (${NODE_OUT})"
    fi

    if pw-cli ls Node 2>/dev/null | grep -q "node.name = \"${NODE_IN}\""; then
        echo "PipeWire: source ${NODE_IN} already present"
    else
        pw-cli create-node adapter "{ factory.name=support.null-audio-sink node.name=${NODE_IN} node.description=\"${NAME}\" media.class=Audio/Source/Virtual object.linger=1 audio.channels=8 audio.position=${pos} }" \
            >/dev/null
        echo "PipeWire: created source \"${NAME}\" (${NODE_IN})"
    fi

    # Optional: route monitor of virtual out → real speakers so you can hear something
    if command -v pw-link >/dev/null 2>&1; then
        # Best-effort; ignore failures if graph layout differs
        pw-link "${NODE_OUT}:monitor_FL" "alsa_output.pci-0000_00_1f.3.analog-stereo:playback_FL" 2>/dev/null || true
        pw-link "${NODE_OUT}:monitor_FR" "alsa_output.pci-0000_00_1f.3.analog-stereo:playback_FR" 2>/dev/null || true
    fi
}

stop_pipewire() {
    if ! command -v pw-cli >/dev/null 2>&1; then
        return 0
    fi

    # Prefer pw-dump (stable JSON) over text scrape of pw-cli ls.
    local ids=""
    if command -v python3 >/dev/null 2>&1 && command -v pw-dump >/dev/null 2>&1; then
        ids="$(
            pw-dump 2>/dev/null | python3 -c '
import json, sys
data = json.load(sys.stdin)
for o in data:
    p = o.get("info", {}).get("props", {}) or {}
    n = p.get("node.name") or ""
    d = p.get("node.description") or ""
    if (n.startswith("JamStudio-Scarlett18i20-")
            or n.startswith("Scarlet18i20-")
            or d == "Scarlett 18i20 USB"):
        print(o.get("id"))
' 2>/dev/null
        )"
    fi

    if [[ -z "${ids}" ]]; then
        # Fallback text scrape
        ids="$(
            pw-cli ls Node 2>/dev/null | awk '
                /^id / { id=$2; gsub(/,/, "", id); next }
                /JamStudio-Scarlett18i20-|Scarlet18i20-|Scarlett 18i20 USB/ {
                    if (id != "") print id
                }
            ' | sort -nu
        )"
    fi

    if [[ -z "${ids}" ]]; then
        echo "PipeWire: no virtual Scarlett nodes found"
        return 0
    fi
    local id
    for id in $ids; do
        if pw-cli destroy "$id" 2>/dev/null; then
            echo "PipeWire: destroyed node id $id"
        fi
    done
}

show_status() {
    echo "=== ALSA ==="
    if [[ -f "$ALSA_SNIPPET" ]]; then
        echo "snippet: $ALSA_SNIPPET (present)"
    else
        echo "snippet: missing"
    fi
    if [[ -f "$ASOUNDRC" ]] && grep -qF "$MARKER_BEGIN" "$ASOUNDRC" 2>/dev/null; then
        echo "asoundrc: managed include active"
    else
        echo "asoundrc: managed include not active"
    fi
    if command -v aplay >/dev/null 2>&1; then
        echo "aplay -L (Scarlett matches):"
        aplay -L 2>/dev/null | grep -i -A1 'scarlett' || echo "  (none — run: $0 start)"
    fi

    echo ""
    echo "=== PipeWire ==="
    if command -v wpctl >/dev/null 2>&1; then
        wpctl status 2>/dev/null | sed -n '/Audio/,/Video/p' | grep -i 'scarlett\|Built-in\|Sinks\|Sources\|Devices' || true
    elif command -v pw-cli >/dev/null 2>&1; then
        pw-cli ls Node 2>/dev/null | grep -i -A3 'scarlett\|Scarlet\|JamStudio-Scarlett' || echo "  (none)"
    else
        echo "  (pw-cli/wpctl not found)"
    fi

    echo ""
    echo "=== Quick test ==="
    echo "  speaker-test -D scarlett18i20 -c 6 -t sine -l 1"
    echo "  # then restart JamStudio → Help → Audio Interface → Rescan"
}

cmd="${1:-status}"

case "$cmd" in
    start)
        ensure_asoundrc_include
        start_pipewire
        echo ""
        echo "Done. Restart JamStudio so it rescans ALSA."
        echo "Help → Audio Interface… should list \"${NAME}\"."
        echo "Plug-and-play: prefer capture on Scarlett, monitor on computer speakers."
        ;;
    stop)
        remove_asoundrc_include
        stop_pipewire
        echo "Done. Restart JamStudio to drop the virtual interface from the list."
        ;;
    alsa)
        ensure_asoundrc_include
        echo "ALSA virtual Scarlett ready. Restart JamStudio."
        ;;
    pipewire)
        start_pipewire
        ;;
    status)
        show_status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|alsa|pipewire}"
        exit 2
        ;;
esac
